### ISSUE TITLE
Package Stabilization Checklist

### ISSUE THREAD

**Issue by klange** [klange/toaruos#135]
The following packages should be stabilized for the 1.0 release. Reliable build scripts, support for dynamic linking, and deployment packages for `get-tools` should be built for them.

- [ ] Lua (should build from upstream without issue - consider adding to the extended toolchain)
- [ ] MuPDF (the cross-compile is particularly odd) and the `toaru-pdfviewer` package
- [ ] SDL
- [ ] prboom (see if we can get audio working)
- [ ] sdlquake
- [ ] Bochs (this may be building correctly from upstream sources these days?)
- [x] Python 3.x (with or without dynlib loading; needs more investigation for locale stuff)
- [ ] libtool (local install and cross-compile, with support shared libraries)

The following libraries need a pass at being built as proper (PIC) shared libraries:
- [ ] zlib
- [ ] libpng
- [ ] freetype
- [ ] cairo
- [ ] ncurses (also panel, etc.)
- [ ] OSMesa (does not build from static libs at all)
- [ ] stdc++ (gnu; part of gcc)
