### ISSUE TITLE
ToaruOS 2.0 Release Roadmap

### ISSUE THREAD

**Issue by klange** [klange/toaruos#205]
Major blockers:
- [ ] Finish the new network stack; we absolutely can not ship a major release without network tools and a functioning package manager.
- [ ] Fix the bootloaders. BIOS loader needs some cleanup, EFI loader needs a new direct 64-bit entry point so we can skip the longmode bootstrap.
- [ ] Maybe recover the ATA/ATAPI drivers.
- [ ] Kernel modules for device drivers? Just build them with the `large` memory model and be done with it, we have all the infrastructure work in place to load them from the filesystem.

Nice-to-have:
- [ ] SMP should probably be stable enough to be usable.
- [ ] Port the rest of the network device drivers.
- [ ] Finish cross-build for gcc, have packages ready for binutils/gcc, Doom, SDL, Quake, maybe mbedTLS.

**Comment by anindyasen** [comment]
Hello,
I found this project quite interesting project for learning OS. 
1. Is this project open for contribution?
2. if yes, then can I work on some this roadmap items as part of 'Hacktoberfest' contributions?

Thank you,

**Comment by klange** [comment]
I prefer contributions to ToaruOS be limited to issue reports and ports. Last year's Hacktoberfest presented a number of challenges for participating projects, and I don't believe ToaruOS's development approach is suited to the event.

**Comment by BasToTheMax** [comment]
Idea: pin this "issue"
