### ISSUE TITLE
AArch64 TODO

### ISSUE THREAD

**Issue by klange** [klange/toaruos#232]
This ticket tracks the status of support for AArch64 in Misaka and the rest of ToaruOS.

As of 2022-02-09, most essential functionality is available. SMP, basic memory management, processes, threads, debug tracing, graphical output, and a set of input devices are available. ToaruOS boots to a full GUI in QEMU, including KVM and HVF hardware virtualization environments.

Remaining work is mostly focused on device support. Interrupt management is missing and there are no supported network or audio devices. No physical hardware platforms are supported at this time.

- [x] Build environment and toolchain
  - [x] Still some quirks with how `libgcc_s.so` is getting linked in userspace, look into this.
    - Weird link script resulted in absolute path (from the host) as the `NEEDED` entry for `libgcc_s.so`. `-l:` fixed it. 
- [x] Essential bringup
  - Stub loader for QEMU's `-machine virt` is ready.
  - Basic memory management API is implemented.
  - System timer is providing a clock source.
  - Ramdisk, filesystem, framebuffer access are working.
  - Userspace is reachable.
  - System call interface is functioning.
- [x] Kernel context switching
- [x] TLS relocations
- [x] `sys_clone()` ABI stuff
- [x] Interrupt management
  - [x] Need a preempt source for timing functions to work.
  - [x] Page fault handlers
  - [ ] CoW
    - Do we have any actual blockers for CoW? How big is our refcount table? I think it's still 1MiB/4GiB.
- [ ] Basic device drivers
  - [x] `virtio-keyboard`, `virtio-tablet`
  - [ ] USB is a necessary thing for real hardware targets.
  - [ ] `virtio-net`
  - [ ] `virtio-gpu` as the Bochs adapter has issues
- [x] SMP
  - [x] Basic core bringup
  - [ ] Fix cache bugs
  - [x] `arch_fatal_prepare`, `arch_fatal` need to stop other cores
    - Should we turn the other cores off with PSCI or send them an IPI like we do on x86-64? 
- [x] Modules
  - [x] Change module builds to use separate sources
  - [x] Implement necessary static object relocations
  - [ ] Possibly move some things (virtio?) to modules
- [ ] Clean up
  - [x] Make sure build makes sense and we haven't broken x86-64.
  - [x] Fix up memory discovery 
  - [x] procfs stuff
  - [x] signal delivery
  - [x] ptrace and debug functions; tracebacks
  - [ ] Fixup hardcoded virt-isms.
  - [ ] Implement stubbed libc functions: `atan2`, `pow`, `fmod`
- [x] Set up AArch64 builds in CI
  - [x] Rebuild Docker image to add aarch64 toolchain
  - [x] Add a new job
- [ ] Other thoughts
  - [ ] Break out the PMM as it is, thus far, entirely generic.
  - [ ] Consider giving the PMM a base address so we can not waste a few kilobytes of bitmap space tracking the 1GiB of device memory in the `virt` machine.
  - [ ] Consider consolidating more of the VMM as it is astoundingly similar between x86-64 and AArch64 with 4K pages.
  - [ ] Port `virtio` input device drivers back to x86-64 (shared module between the two arches?) 

![Screenshot from 2022-01-29 07-56-03](https://user-images.githubusercontent.com/223546/151644948-523040af-c4ed-4f81-90d3-cfaa1a0c66c5.png)
![Screenshot from 2022-01-29 10-23-19](https://user-images.githubusercontent.com/223546/151644945-2b58219f-b38a-4b4b-b3cf-5b7530e5c909.png)
![Screenshot from 2022-01-29 19-15-17](https://user-images.githubusercontent.com/223546/151657938-7b0efc17-8e15-48b8-9b55-f0c8f12cf142.png)
![](https://klange.dev/s/Screenshot%20from%202022-02-01%2007-30-01.png)
![](https://klange.dev/s/Screenshot%20from%202022-02-03%2008-19-43.png)
