### ISSUE TITLE
ToaruOS 2.2 Roadmap

### ISSUE THREAD

**Issue by klange** [klange/toaruos#258]
This is primarily functionality deferred from 2.1:

- [ ] Expand package availability for AArch64 target
  - [ ] Improve package manager support for architecture-specific packages 
- [ ] Basic support for USB HID devices on Raspberry Pi 400
  - [ ] Essential xhci host controller support. _Try to make sure this is applicable to other platforms._
  - [ ] USB hub, keyboard, mouse drivers
  - [ ] USB tablet drivers? (test with 55" infrared touch frame)
- [ ] `genet` network support for RPi400?

**Comment by klange** [comment]
Closing this as 2.2 was released a while ago.
