### ISSUE TITLE
1.0.0 Tracking Ticket

### ISSUE THREAD

**Issue by klange** [klange/toaruos#34]
- [x] GCC port
- [x] Audio device drivers
- [x] Audio subsystem
- [x] ATAPI CD support (CD filesystem?)
- [X] Network stack
- [x] New wallpaper and character assets
- [x] Networking samples (telnet, etc.)
- [x] SDL backend + port
- [x] Stable ext2 writes
- [x] Dynamic loader
- [x] Finish Python port
- [x] Toolkit (Python?)
- [x] VFS permissions (basic)

**Comment by klange** [comment]
Considering add VFS permissions as a 1.0 target. It's not something I've looked at in a while.
