### ISSUE TITLE
Network Tracking Ticket

### ISSUE THREAD

**Issue by klange** [klange/toaruos#44]
This is a task list ticket for tracking progress on the network stack.
- [ ] Packet construction
  - [x] Ethernet frames
  - [x] IPv4 headers
  - [x] UDP packets
    - [ ] UDP packet checksums
  - [x] TCP packets
- [ ] Core protocol support
  - [x] ARP
  - [x] DHCP
    - [x] DHCP packet construction
    - [x] DHCP packet interpretation (options)
  - [x] DNS
    - [x] Request generation
    - [x] Response parsing
  - [x] IRC
  - [x] Telnet
- [x] Userspace interface
